name: Policy States Collector
# description: Tests and deploys the Policy States Collector code

on:
  workflow_dispatch:
    inputs:
      functionAppName:
        description: "function app name that was created by infrastructure deployment workflow"
        required: true
        type: string
env:
  PYTHON_VERSION: "3.9"

concurrency:
  # Serializing this workflow.
  group: ${{ github.workflow }}

jobs:
  test:
    name: Test function app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: 'policy-states-collector/requirements.txt'

      - name: Install dependencies
        working-directory: ./policy-states-collector
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Test with pytest
        working-directory: ./policy-states-collector
        run: |
          pytest PolicyStates -v

  app:
    name: Deploy function app
    runs-on: ubuntu-latest
    needs: [infra]
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        run: |
          az login --identity -u ${{ changeme }}
          az account set -s ${{ vars.SUBSCRIPTION_NAME }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Resolve function dependencies
        working-directory: ./policy-states-collector
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Deploy policy states collector function app
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ github.event.inputs.functionAppName }}
          package: ./policy-states-collector

      - name: Show function invoke URL
        run: |
          invoke_url=$(az functionapp function show \
            -g ${{ vars.RESOURCE_GROUP_NAME }} \
            -n ${{ github.event.inputs.functionAppName }} \
            --function-name NotificationHandler \
            -o tsv --query invokeUrlTemplate)

          echo "✅ Function invoke URL: $invoke_url"
